'use strict';

const GET_USER_DEFAULT = 'GET_USER_DEFAULT';
const UPDATE_REGISTER_FORM = 'UPDATE_REGISTER_FORM';
const UPDATE_LOGIN_FORM = 'UPDATE_LOGIN_FORM';
const UPDATE_USER_INFO_FORM = 'UPDATE_USER_INFO_FORM';
const REGISTER = 'REGISTER';
const ACTIVATE_ACCOUNT = 'ACTIVATE_ACCOUNT';
const LOGIN = 'LOGIN';
const LOGOUT = 'LOGOUT';
const UPDATE_USER_INFO = 'UPDATE_USER_INFO'

module.exports = {
    GET_USER_DEFAULT,
    UPDATE_REGISTER_FORM,
    UPDATE_LOGIN_FORM,
    UPDATE_USER_INFO_FORM,
    REGISTER,
    ACTIVATE_ACCOUNT,
    LOGIN,
    LOGOUT,
    UPDATE_USER_INFO,
};
