'use strict';

const GET_USER_DEFAULT = 'GET_USER_DEFAULT';
const UPDATE_REGISTER_FORM = 'UPDATE_REGISTER_FORM';
const UPDATE_LOGIN_FORM = 'UPDATE_LOGIN_FORM';
const REGISTER = 'REGISTER';
const LOGIN = 'LOGIN';
const LOGOUT = 'LOGOUT'

module.exports = {
    GET_USER_DEFAULT,
    UPDATE_REGISTER_FORM,
    UPDATE_LOGIN_FORM,
    REGISTER,
    LOGIN,
    LOGOUT,
};
